on:
  push:
    branches:
      - master

name: Deploy to GitHub Pages

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
        architecture: x64
    - run: |
        cd docs
        pip install sphinx git+https://github.com/AccentDesign/karma_sphinx_theme.git releases
        make html
        cd _build/html
        touch .nojekyll
    - name: GitHub Pages Deploy
      uses: maxheld83/ghpages@v0.2.1
      env:
        GH_PAT: ${{ secrets.GH_PAT }}
        BUILD_DIR: docs/_build/html/